### ISSUE TITLE
Services should automatically restart on crash

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/doltlab-issues#124]
Services should restart automatically, something like:
```yaml
services:
  my-service:
    image: my-image
    restart: on-failure
```
