### ISSUE TITLE
doltabenvoy image lack environment key in the docker-compose.yaml

### ISSUE THREAD

**Issue by SWHL** [dolthub/doltlab-issues#42]
- When I ran the `start-doltlab.sh`, I met that the `doltlab-doltlabenvoy-1` container can't run successfully.
- I solved the question by adding the `environment `, for details:
  ```yaml
  # docker-compose.yaml
   doltlabenvoy:
       image: envoyproxy/envoy-alpine:v1.18-latest
       environment:   # this 
         - "ENVOY_UID=0"
       command:
         -c /envoy.yaml
       ports:
         - "100:100"
         - "80:80"
         - "4321:4321"
         - "7770:7770"
       networks:
         - default
       volumes:
         - ${PWD}/envoy.yaml:/envoy.yaml
  ```
- Refer [envoyproxy/envoy/issues/11506](https://github.com/envoyproxy/envoy/issues/11506), hope to help someone.
